# Generated by Django 4.2 on 2023-04-27 17:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='zapis',
            name='comment',
            field=models.CharField(blank=True, max_length=3000, null=True, verbose_name='Комментарий пользователя'),
        ),
    ]
