# Generated by Django 4.2 on 2023-04-27 21:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_alter_zapis_date'),
    ]

    operations = [
        migrations.CreateModel(
            name='Back',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_back', models.CharField(blank=True, max_length=255, null=True, verbose_name='Имя')),
                ('email_back', models.CharField(blank=True, max_length=255, null=True, verbose_name='email')),
                ('phone_back', models.CharField(blank=True, max_length=255, null=True, verbose_name='Телефон')),
            ],
            options={
                'verbose_name': 'Обратный звонок',
                'verbose_name_plural': 'Обратные звонки',
            },
        ),
        migrations.AlterField(
            model_name='zapis',
            name='name',
            field=models.CharField(default=20, max_length=255, verbose_name='Имя'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='zapis',
            name='phone',
            field=models.CharField(default=20, max_length=255, verbose_name='Телефон'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='zapis',
            name='type_photoset',
            field=models.IntegerField(choices=[(0, 'Индивидуальная'), (1, 'Семейная'), (2, 'Парная'), (3, 'Видеоролики с фото'), (4, 'Детская'), (5, 'Мероприятия'), (6, 'Животные'), (7, 'Коллаж')], default=20, verbose_name='Тип фотосессии'),
            preserve_default=False,
        ),
    ]
