# Generated by Django 4.2 on 2023-04-27 22:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_back_alter_zapis_name_alter_zapis_phone_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='back',
            name='email_back',
            field=models.CharField(max_length=255, verbose_name='email'),
        ),
        migrations.AlterField(
            model_name='back',
            name='name_back',
            field=models.CharField(max_length=255, verbose_name='Имя'),
        ),
        migrations.AlterField(
            model_name='back',
            name='phone_back',
            field=models.CharField(max_length=255, verbose_name='Телефон'),
        ),
    ]
